import ispHeader_7_ from './ispHeader.js';import stepper1_9_ from './stepper1.js';import panelRegole_38_ from './panelRegole.js';import table1_42_ from './table1.js';import modal1_54_ from './modal1.js';
export default function page1() {
var root = document.createElement('div');
root.style.flex = '1 1 0';
root.style.backgroundColor = 'white';
root.style.overflow = 'auto';
root.style.display = 'flex';
root.style.flexDirection = 'column';
var div_6 = document.createElement('div');
var ispHeader_7 = ispHeader_7_();
var div_8 = document.createElement('div');
div_6.appendChild(ispHeader_7);
var stepper1_9 = stepper1_9_();
var div_10 = document.createElement('div');
div_8.appendChild(stepper1_9);
var flex = document.createElement('display');
var column = document.createElement('flexDirection');
var div_13 = document.createElement('div');
var h3_14 = document.createElement('h3');
h3_14.style.textAlign = 'center';
var textNode_16 = document.createTextNode('Selezione firmatari');
h3_14.append(textNode_16);
var p_17 = document.createElement('p');
div_13.appendChild(h3_14);
p_17.style.textAlign = 'center';
var textNode_19 = document.createTextNode('lorem ipsum lorem ipsum');
p_17.append(textNode_19);
var div_20 = document.createElement('div');
div_13.appendChild(p_17);
div_10.appendChild(flex);
div_10.appendChild(column);
div_10.appendChild(div_13);
var p_21 = document.createElement('p');
var textNode_22 = document.createTextNode('Nome azienda principale');
p_21.append(textNode_22);
var div_23 = document.createElement('div');
div_20.appendChild(p_21);
div_10.appendChild(div_20);
var select_24 = document.createElement('select');
var option_25 = document.createElement('option');
var textNode_26 = document.createTextNode('Potere 1');
option_25.append(textNode_26);
var option_27 = document.createElement('option');
select_24.appendChild(option_25);
var textNode_28 = document.createTextNode('Potere 2');
option_27.append(textNode_28);
var option_29 = document.createElement('option');
select_24.appendChild(option_27);
var textNode_30 = document.createTextNode('Potere 3');
option_29.append(textNode_30);
var div_31 = document.createElement('div');
select_24.appendChild(option_29);
div_23.appendChild(select_24);
div_10.appendChild(div_23);
div_31.style.display = 'flex';
div_31.style.flexDirection = 'column';
var div_34 = document.createElement('div');
var h3_35 = document.createElement('h3');
var textNode_36 = document.createTextNode('Title elenco firmatari');
h3_35.append(textNode_36);
var div_37 = document.createElement('div');
div_34.appendChild(h3_35);
div_31.appendChild(div_34);
var panelRegole_38 = panelRegole_38_();
var div_39 = document.createElement('div');
div_37.appendChild(panelRegole_38);
div_39.style.display = 'flex';
div_39.style.justifyContent = 'center';
var table1_42 = table1_42_();
var div_43 = document.createElement('div');
div_39.appendChild(table1_42);
div_31.appendChild(div_37);
div_31.appendChild(div_39);
div_10.appendChild(div_31);
div_43.style.display = 'flex';
div_43.style.justifyContent = 'space-between';
var button_46 = document.createElement('button');
var textNode_47 = document.createTextNode('ANNULLA');
button_46.append(textNode_47);
var button_48 = document.createElement('button');
div_43.appendChild(button_46);
var textNode_49 = document.createTextNode('CONTINUA');
button_48.append(textNode_49);
button_48.onclick = ev => {eventManager('page1BtnContinuaClicked')};
var div_51 = document.createElement('div');
div_43.appendChild(button_48);
root.appendChild(div_6);
root.appendChild(div_8);
root.appendChild(div_10);
root.appendChild(div_43);
var p_52 = document.createElement('p');
var textNode_53 = document.createTextNode('SALVA E RIPRENDI IN SEGUITO');
p_52.append(textNode_53);
var modal1_54 = modal1_54_();
div_51.appendChild(p_52);
root.appendChild(div_51);
root.appendChild(modal1_54);
//import {table} from '../lib/html.js';
//var tableFirmatari = table([{nome:'rossi mario', cf:'RSAMRI76A45C345Y', ibiz:'SI', ndce:'NO', grafo:'NO', gruppo:'Gruppo A', peso:'50%'},{nome:'rossi mario', cf:'RSAMRI76A45C345Y', ibiz:'SI', ndce:'NO', grafo:'NO', gruppo:'Gruppo A', peso:'50%'}]);
//table1.append(tableFirmatari);
/********************************* PUBLIC ********************************************* */
root.blur = (ev) => {
	root.classList.add("blur");
}
root.unblur = (ev) => {
	root.classList.remove("blur");
}
document.register('elencoFirmatariBlur', root.blur)
return root;}