export default function panelRegole() {
var root = document.createElement('div');
root.style.display = 'grid';
root.style.gridTemplateColumns = '1fr 1fr 1fr';
root.style.gridGap = '50px';
root.style.justifyContent = 'center';
root.style.textAlign = 'center';
var div_6 = document.createElement('div');
div_6.style.border = '1px solid blue';
var p_8 = document.createElement('p');
var textNode_9 = document.createTextNode('lorem 1');
p_8.append(textNode_9);
var img_10 = document.createElement('img');
img_10.src = './img/done_black.png';
var div_12 = document.createElement('div');
var p_13 = document.createElement('p');
var textNode_14 = document.createTextNode('lorem 2');
p_13.append(textNode_14);
var img_15 = document.createElement('img');
img_15.src = './img/done_black.png';
var div_17 = document.createElement('div');
var p_18 = document.createElement('p');
var textNode_19 = document.createTextNode('lorem 3');
p_18.append(textNode_19);
var div_20 = document.createElement('div');
var p_21 = document.createElement('p');
var textNode_22 = document.createTextNode('lorem 4');
p_21.append(textNode_22);
var div_23 = document.createElement('div');
var p_24 = document.createElement('p');
var textNode_25 = document.createTextNode('lorem 5');
p_24.append(textNode_25);
var div_26 = document.createElement('div');
var p_27 = document.createElement('p');
var textNode_28 = document.createTextNode('lorem 6');
p_27.append(textNode_28);
return root;}